# Generated by Django 4.1.4 on 2023-01-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagriskele', '0003_alter_building_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='covered_gross',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Covered Gross Area'),
        ),
    ]
