# Generated by Django 4.1.4 on 2023-01-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagriskele', '0004_alter_apartment_covered_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='balcony',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Balcony area sqm'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='covered_gross',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Covered Gross Area'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_in_gbp',
            field=models.IntegerField(default=10000),
        ),
    ]
