# Generated by Django 4.1.5 on 2023-01-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagriskele', '0005_alter_apartment_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='balcony',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Balcony area sqm'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='covered_gross',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Covered Gross Area'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_in_gbp',
            field=models.IntegerField(),
        ),
    ]
