# Generated by Django 4.1.5 on 2023-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagriskele', '0007_alter_apartment_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price_in_gbp',
            field=models.IntegerField(null=True),
        ),
    ]
