# Generated by Django 4.1.4 on 2023-01-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fagriskele', '0002_alter_apartment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
    ]
